export const EMOCIONES = [
  {
    nombre: 'Alegría',
    emoji: '😄',
    color: 'bg-yellow-400',
    colorHex: '#facc15',
    textColor: 'text-yellow-400',
    borderColor: 'border-yellow-400',
    ringColor: 'ring-yellow-400',
    gradientFrom: 'from-yellow-400',
    gradientTo: 'to-amber-300',
    descripcion: 'Felicidad, entusiasmo, gratitud',
  },
  {
    nombre: 'Tristeza',
    emoji: '😢',
    color: 'bg-blue-500',
    colorHex: '#3b82f6',
    textColor: 'text-blue-400',
    borderColor: 'border-blue-400',
    ringColor: 'ring-blue-400',
    gradientFrom: 'from-blue-500',
    gradientTo: 'to-cyan-400',
    descripcion: 'Melancolía, pérdida, nostalgia',
  },
  {
    nombre: 'Furia',
    emoji: '😡',
    color: 'bg-red-600',
    colorHex: '#dc2626',
    textColor: 'text-red-500',
    borderColor: 'border-red-500',
    ringColor: 'ring-red-500',
    gradientFrom: 'from-red-600',
    gradientTo: 'to-orange-500',
    descripcion: 'Enojo, frustración, rabia',
  },
  {
    nombre: 'Temor',
    emoji: '😨',
    color: 'bg-purple-500',
    colorHex: '#a855f7',
    textColor: 'text-purple-400',
    borderColor: 'border-purple-400',
    ringColor: 'ring-purple-400',
    gradientFrom: 'from-purple-500',
    gradientTo: 'to-violet-400',
    descripcion: 'Miedo, inseguridad, preocupación',
  },
  {
    nombre: 'Desagrado',
    emoji: '🤢',
    color: 'bg-green-500',
    colorHex: '#22c55e',
    textColor: 'text-green-400',
    borderColor: 'border-green-400',
    ringColor: 'ring-green-400',
    gradientFrom: 'from-green-500',
    gradientTo: 'to-emerald-400',
    descripcion: 'Repulsión, disgusto, rechazo',
  },
  {
    nombre: 'Ansiedad',
    emoji: '😰',
    color: 'bg-orange-400',
    colorHex: '#fb923c',
    textColor: 'text-orange-400',
    borderColor: 'border-orange-400',
    ringColor: 'ring-orange-400',
    gradientFrom: 'from-orange-400',
    gradientTo: 'to-yellow-400',
    descripcion: 'Nerviosismo, tensión, incertidumbre',
  },
  {
    nombre: 'Envidia',
    emoji: '😒',
    color: 'bg-teal-500',
    colorHex: '#14b8a6',
    textColor: 'text-teal-400',
    borderColor: 'border-teal-400',
    ringColor: 'ring-teal-400',
    gradientFrom: 'from-teal-500',
    gradientTo: 'to-cyan-400',
    descripcion: 'Celos, comparación, deseo',
  },
  {
    nombre: 'Ennui',
    emoji: '😑',
    color: 'bg-indigo-400',
    colorHex: '#818cf8',
    textColor: 'text-indigo-400',
    borderColor: 'border-indigo-400',
    ringColor: 'ring-indigo-400',
    gradientFrom: 'from-indigo-400',
    gradientTo: 'to-slate-400',
    descripcion: 'Aburrimiento, hastío, apatía',
  },
  {
    nombre: 'Vergüenza',
    emoji: '😳',
    color: 'bg-pink-500',
    colorHex: '#ec4899',
    textColor: 'text-pink-400',
    borderColor: 'border-pink-400',
    ringColor: 'ring-pink-400',
    gradientFrom: 'from-pink-500',
    gradientTo: 'to-rose-400',
    descripcion: 'Rubor, incomodidad, culpa',
  },
]

export const getEmocion = (nombre) => EMOCIONES.find(e => e.nombre === nombre)
